"""addded many to one relationship

Revision ID: 9d7d7aa004fc
Revises: 2dfb8e56966f
Create Date: 2020-12-16 07:58:08.002932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d7d7aa004fc'
down_revision = '2dfb8e56966f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('theme_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'images', 'themes', ['theme_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.drop_column('images', 'theme_id')
    # ### end Alembic commands ###
